### ISSUE TITLE
[REJECTED] Pale Moon support

### ISSUE THREAD

**Issue by sergeevabc** [aeris/enjoy-reading#1]
Dear @aeris, your extension is based on Jetpack which makes it [incompatible](https://forum.palemoon.org/viewtopic.php?t=8740) with [Pale Moon](https://www.palemoon.org/roadmap.shtml), the most promising fork of Firefox out there. However [it welcomes XUL](https://www.palemoon.org/dev/addon-sdk/). Could you explore the possibility of supporting the broader reading audience, including Pale Moon users?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by aeris** [comment]
Hello, sorry for the latency.
I took the maintenance of this add-on only to remove all not authorizated API call to validate the add-on through Mozilla review.
Currently, this add-on is heavily tied to Jetpack with a lot of third party code, so even if code is simple porting to XUL seems complicated :'(

**Comment by sergeevabc** [comment]
Thanks for letting me know about it. Happy New year.
